Change of github action-integrate.yml Github action use docker file instead of building all dependencies separately

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -11,9 +11,12 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
     - uses: actions/checkout@v4
-    - name: Install Boost
-      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
-    - name: Generate CMake
-      run: cmake -B ${{github.workspace}}/build
-    - name: Build project
-      run: cmake --build ${{github.workspace}}/build
+    - name: Docker version
+      run: docker --version
+    - name: Docker build
+      run: |
+        docker build -t app .
+        if [ $? -ne 0 ]; then
+          echo "Docker build failed"
+          exit 1 
+        fi
